name: Release

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - run: dotnet pack -c Release
    - run: dotnet nuget push bin/Release/*.nupkg -k $NUGET_OLG_API_KEY -s https://api.nuget.org/v3/index.json
      env:
        NUGET_OLG_API_KEY: ${{ secrets.NUGET_OLG_API_KEY }}
