name: Release

on:
  push:
    branches:
      - master
      - alpha
      - beta
    tags:
      - '!*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1.2.0
      with:
        node-version: 12

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - run: npm i && npx semantic-release@beta
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        GH_TOKEN: ${{secrets.GH_TOKEN}}
